esphome:
  name: co2-internal

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "abcdefg-changeme"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2-Internal Fallback Hotspot"
    password: "abcdefg-changeme"

captive_portal:
i2c:
  sda: SDA
  scl: SCL
  scan: True
  frequency: 50kHz
  
sensor:
  - platform: scd30
    co2:
      name: "Inside CO2"
      accuracy_decimals: 1
    temperature:
      name: "Inside Temperature"
      accuracy_decimals: 2
    humidity:
      name: "Inside Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 15s
    automatic_self_calibration: true
    
